packages:
  - apps/*
  - libs/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - contentlayer
  - cypress
  - esbuild
  - nx
  - protobufjs
  - sharp
  - unrs-resolver
